# Docker compose version
version: "3"

# Services
services: 
    app: # Name of service
        build:
            context: . # Current directory
        ports:
            - "8000:8000" # host:image ports
        volumes: # Map source code to location in Docker (will automatically pull changes)
            - ./app:/app
        command: >
            sh -c "python manage.py wait_for_db && 
                    python manage.py migrate &&
                    python manage.py runserver 0.0.0.0:8000"
        environment: 
            - DB_HOST=db
            - DB_NAME=app
            - DB_USER=postgres
            - DB_PASS=supersecretpassword
        depends_on: 
            - db
    
    db:
        image: postgres:10-alpine
        environment: 
            - POSTGRES_DB=app
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=supersecretpassword